name       : wireshark
version    : 2.0.2
release    : 6
source     :
    - https://solus-project.com/sources/wireshark-2.0.2.tar.bz2 : e921fb072085a5654d899949bb561d0687f4819f7b63ba35777bb949a9b6b9c1
license    : 
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
summary    : Wireshark
description: |
    Wireshark
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gtk+-3.0)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
