name       : wireshark
version    : 2.0.1
release    : 5
source     :
    - https://solus-project.com/sources/wireshark-2.0.1.tar.bz2 : c9bd07dd0d0045d6ca7537390a1afbcdf33716d193ea7d7084ae4f6c30b683ab
license    : 
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
summary    : Wireshark
description: |
    Wireshark
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gtk+-3.0)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
