name       : wireshark
version    : 2.4.5
release    : 25
source     :
    - https://1.na.dl.wireshark.org/src/wireshark-2.4.5.tar.xz : b3b2ec29fba0f4a3a590438abe4054e56f19108d440fc2d61492db9d8ff16fd7
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
