name       : wireshark
version    : 2.2.3
release    : 13
source     :
    - https://1.eu.dl.wireshark.org/src/wireshark-2.2.3.tar.bz2 : 97bac89e88892054a5848a9f7e0c36aa399a2008900829b078e29cab0ddd593b
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
