name       : wireshark
version    : 3.4.7
release    : 61
source     :
    - https://gitlab.com/wireshark/wireshark/-/archive/wireshark-3.4.7/wireshark-wireshark-3.4.7.tar.bz2 : d78e68df90356cc617536c5dedd8d05082c6beee0dbc016ac9e01a9a8257a8dd
homepage   : https://www.wireshark.org/
license    :
    - GPL-2.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libbrotlicommon)
    - pkgconfig(libcares)
    - pkgconfig(libgcrypt)
    - pkgconfig(liblz4)
    - pkgconfig(libmaxminddb)
    - pkgconfig(libnghttp2)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(libssh)
    - pkgconfig(libzstd)
    - pkgconfig(lua-5.1)
    - pkgconfig(minizip)
    - pkgconfig(opus)
    - pkgconfig(sbc)
    - pkgconfig(speexdsp)
    - snappy-devel
rundeps    :
    - qt5-multimedia
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 $pkgfiles/wireshark.sysusers $installdir/%libdir%/sysusers.d/wireshark.conf
    chmod 750  $installdir/usr/bin/dumpcap
    chown :150 $installdir/usr/bin/dumpcap
