name       : wireshark
version    : 1.12.7
release    : 1
source     :
    - http://solus-us.tk/sources/wireshark-1.12.7.tar.bz2 : c74a1c14e72ce0f198a93d832e71742c7f312cbbe719e5def9ecef176860f92c
license    : 
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
summary    : Wireshark
description: |
    Wireshark
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gtk+-3.0)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
