name       : wireshark
version    : 1.12.8
release    : 2
source     :
    - http://solus-us.tk/sources/357e0a4e49525d80cdc740bb16539fcdb526ad38cc2ed6cabedafc9bdee5c7e7/wireshark-1.12.8.tar.bz2 : 357e0a4e49525d80cdc740bb16539fcdb526ad38cc2ed6cabedafc9bdee5c7e7
license    : 
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
summary    : Wireshark
description: |
    Wireshark
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gtk+-3.0)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
