name       : wireshark
version    : 2.6.6
release    : 33
source     :
    - https://github.com/wireshark/wireshark/archive/v2.6.6.tar.gz : 8f07d6586483c42163cbb0dc708a2524609c16341f8ea640e5e76ba12d655b8d
license    :
    - GPL-2.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libgcrypt-devel
    - libpcap-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install

    install -D -m 00644 $pkgfiles/wireshark.sysusers $installdir/%libdir%/sysusers.d/wireshark.conf
    chmod 750  $installdir/usr/bin/dumpcap
    chown :150 $installdir/usr/bin/dumpcap
