name       : wireshark
version    : 2.0.5
release    : 8
source     :
    - https://1.na.dl.wireshark.org/src/wireshark-2.0.5.tar.bz2 : 0ce0241330828973f5b4efee422a3760cab8ce0b41e7721c4b9fd185be1bb10b
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gtk+-3.0)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
