name       : wireshark
version    : 2.0.3
release    : 7
source     :
    - https://1.na.dl.wireshark.org/src/wireshark-2.0.3.tar.bz2 : e196376e75fe21fdef41b4eaa27ce2e1b2b561e7f7b20328a8e96657cc4465fc
license    : 
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
summary    : Wireshark
description: |
    Wireshark
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gtk+-3.0)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
