name       : wireshark
version    : 2.4.4
release    : 24
source     :
    - https://1.na.dl.wireshark.org/src/wireshark-2.4.4.tar.xz : 049a758e39422dcd536d7f75cebbfaa44e4f305d602bf22964d6459821126f58
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
