name       : wireshark
version    : 2.2.5
release    : 16
source     :
    - https://2.na.dl.wireshark.org/src/wireshark-2.2.5.tar.bz2 : 75dd88d3d6336559e5b0b72077d8a772a988197d571f00029986225fef609ac8
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
