name       : wireshark
version    : 3.4.2
release    : 55
source     :
    - https://gitlab.com/wireshark/wireshark/-/archive/wireshark-3.4.2/wireshark-wireshark-3.4.2.tar.bz2 : d30ebe728ecea0f9ebe92085cc89797e58fc8bcb8b093f639c606d31178ee262
license    :
    - GPL-2.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(libssh)
    - pkgconfig(lua-5.1)
    - libgcrypt-devel
rundeps    :
    - qt5-multimedia
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -D -m 00644 $pkgfiles/wireshark.sysusers $installdir/%libdir%/sysusers.d/wireshark.conf
    chmod 750  $installdir/usr/bin/dumpcap
    chown :150 $installdir/usr/bin/dumpcap
