name       : wireshark
version    : 2.6.2
release    : 28
source     :
    - https://1.na.dl.wireshark.org/src/wireshark-2.6.2.tar.xz : 49b2895ee3ba17ef9ef0aebfdc4d32a778e0f36ccadde184516557d5f3357094
license    :
    - GPL-2.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    install -D -m 00644 $pkgfiles/wireshark.sysusers $installdir/%libdir%/sysusers.d/wireshark.conf
    chmod 750  $installdir/usr/bin/dumpcap
    chown :150 $installdir/usr/bin/dumpcap
