name       : wireshark
version    : 2.4.3
release    : 23
source     :
    - https://1.na.dl.wireshark.org/src/wireshark-2.4.3.tar.xz : 189495996b68940626cb53b31c8902fa1bb5a96b61217cea42734c13925ff12e
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
