name       : wireshark
version    : 3.0.7
release    : 44
source     :
    - https://github.com/wireshark/wireshark/archive/v3.0.7.tar.gz : c0e448199b0153bad9f3698242db25f59952306bc1074acc83b40b33ccb98280
license    :
    - GPL-2.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libcares)
    - pkgconfig(liblz4)
    - pkgconfig(libnghttp2)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(libssh)
    - pkgconfig(lua-5.1)
    - libgcrypt-devel
rundeps    :
    - qt5-multimedia
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -D -m 00644 $pkgfiles/wireshark.sysusers $installdir/%libdir%/sysusers.d/wireshark.conf
    chmod 750  $installdir/usr/bin/dumpcap
    chown :150 $installdir/usr/bin/dumpcap
