name       : wireshark
version    : 2.2.2
release    : 12
source     :
    - https://1.eu.dl.wireshark.org/src/wireshark-2.2.2.tar.bz2 : f9acef5e9a9021a400b4244fafc06969f41ec594ec57fd7f0ff63bafca0055b3
license    :
    - GPL-2.0
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : no
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
